### ISSUE TITLE
ALTUI  dim level not updated

### ISSUE THREAD

**Issue by sle118** [vwout/vera-tradfri#1] opened 2021-01-08 17:30 UTC
First of all, thank you for working on this plugin; it was enough motivation to hit the purchase button and start taming the Tradfri devices I have around the home!

I wanted to draw your attention to a chance you made which I believe might be causing some display issues in ALTUI.
https://github.com/vwout/vera-tradfri/blob/1e25a6ad59d923896d0e5ddff2e5ca626782e130/L_TradfriGW.lua#L778

Seems like ALTUI will show "LoadLevelStatus" when looking at the control panel of a given device, but it will show LoadLevelTarget on the main device page.  This means the plugin should probably update both variables when an "observe" message is received.

I could go ahead and clone your repo, then make the change myself if you want some help.  Let me know.

**Comment by vwout** [comment] 2021-01-09 14:28
You are correct, LoadLevelStatus should be set and LoadLevelTarget should be updated, otherwise AltUI will continue to show the LoadLevelTarget in the control panel. AltUI uses the value of LoadLevelTarget for display if it exists and falls back to LoadLevelStatus to make sure the last value set on the UI is immediately visible. On the overview page LoadLevelStatus is used, which means both need to be set. This also applies to the other Status/Target attributes.
In addition, the code contains a logic error, prevent all variables from being updated correctly at all times.

**Comment by vwout** [comment] 2021-01-09 14:38
The issue is resolved in release 0.5.0.

**Closed as completed** 2021-01-09 15:47 UTC
